# Site settings
title: My data site
description:
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
include: ""

# Build settings
markdown: kramdown
gems:
  - 'jekyll/scholar'

# Options for jekyll-scholar:
scholar:
  style: cell
